### PR TITLE
openssl: Support older TLS and DH key

### LINKED ISSUE #1641: Error: "SSL_connect returned=1 errno=0 state=error: dh key too small"
First of all i want you to know that before i opened this issue i looked if it was reported by someone else and i already applied those solutions without success.
The problem seems to be that postal refuses to send emails to servers which have SSL with weak Cipher.
I run the command **openssl s_client** on two mail servers to which we can send emails and to which we cannot. The difference i found is in the TLS version and Cypher of their SSL certificate. The failed one has TLS v1.2 Cypher DHE-RSA-AES256-SHA256 (which is weak) and the other TLSv1.3 Cypher TLS_AES_256_GCM_SHA384 (which is recommended). 
This results in a **Ephemeral Diffie-Hellman Key** too small for the failed server **Server Temp Key: DH, 1024 bits**
How can we tell Postal to still communicate with servers when Server Temp Key is small?

I am using v2 of Postal.

### PR DESCRIPTION
**Pull request by dragoangel**
Resolves #1641

### CODE REVIEW

**Comment by dragoangel** [comment]
Due to SMTP is much less optimistic in terms of new encryption standards and due to fallback to plaintext - better to have TLSv1.0 then plaintext. Small DH key at this time work as DoS at all.

**Comment by dragoangel** [comment]
Guys DEFAULT@SECLEVEL=2 for mail is too much...

**Comment by catphish** [comment]
We have discussed this and come to the conclusion that reducing the TLS security level of the whole system should not be necessary. Instead, we have implemented falling back to unencrypted transport when sending, but have chosen to maintain the stronger security for inbound connections.
See 0dc6824a8f0315ea42b08f7e6812b821b62489c9 for the alternative.

**Comment by dragoangel** [comment]
So fallback to unencrypted connection is more secure than at least some encryption? Very strange :/, sorry I don't get it

**Comment by catphish** [comment]
> Falling back is must be in place as by smtp standards, but I still think for speaking with pubic MX is better with at least tls1.0 then with plain. For clients - encryption could be mandatory, without option to fallback and more strict encryption settings, e.g.: TLSv1.2 minimum.
You're absolutely correct of course. Opportunistic encryption is marginally more secure than no encryption. If someone wants to write the code for this *and* they can justify that changing the TLS settings system-wide will not reduce the security of other protocols, then it may well be worth considering. However, in the meantime I consider opportunistic SMTP encryption to be so weak that it's not worth compromising the security of any other part of the system to support it.
It would be much better if openssl's settings could be overridden for the opportunistic sending process only, but your reply implies that this isn't possible :(

**Pull request closed without merging**
