### PR TITLE
Feat/add show message content config parameter

### PR DESCRIPTION
**Pull request by belghitioth**
I am trying to use Postal for one of my client to manage our business needs but we don't want to display messages information as it is sensitive data.

I would like to add a private/public mode to Postal in order to not display sensitive content from emails such as attachments, plain text, plain html. 

Using one new variable in the file `config/postal.defaults.yml`

`show_message_content: false` to not display sensitive data from incoming and outgoing messages

**show_message_content: false**

Capture d’écran 2022-12-12 à 13 48 33
Capture d’écran 2022-12-12 à 13 50 04

**show_message_content: true**
Capture d’écran 2022-12-12 à 15 00 37

### CODE REVIEW

**Comment by willpower232** [comment]
Nice idea :ok_hand:

**Comment by catphish** [comment]
Thanks for making a pull request for this. I have a couple of outstanding thoughts / questions for discussion on this:

1) Should this feature be implemented per user, rather than globally? I'd imagine most people would want some users to see the message content while other users are restricted to viewing the metadata.
2) Is the routes file a valid place to secure these actions? Perhaps if configured globally, this makes sense, but I'd be inclined to lock down the controller too.

Anyone else have an opinion on this?

**Comment by willpower232** [comment]
1. makes sense

2. adding checks to the controller instead of the routes file would be easier to write tests for I imagine, I guess the difference is negligible unless people tend to write multiple routes to the same controller functions in rails #NoIdea

**Comment by adamcooke** [comment]
I'd prefer to see this not configured as a permission on users rather than just a global setting.

**Comment by catphish** [comment]
> I'd prefer to see this not configured as a permission on users rather than just a global setting.

I'd prefer to see this comment make sense.

**Comment by rodelrod** [comment]
Having a global option does not preclude adding a per-user option in the future. This is a must-have feature for many environments that I was also waiting to see merged.

**Pull request closed without merging**
