### PR TITLE
Requeue Held Messages once a hour

### LINKED ISSUE #144: Send limit improvements
Hello,

Having just now tried the "Send limit" system, I found it pretty strict. Here are a few suggestions of options that could be given to administrators:

- Allow to completely disable the limit. I tried putting 0 or -1 as the limit but that just blocked all messages instantly.
- Allow automatic releasing of held messages once the number of messages went back below the maximum. This would make for a simple rate limiting feature
- Add a complete rate limiting system, allowing custom rules (like IP pool rules but this time for rate limits): limit mails towards X domain but not Y domain etc...

### PR DESCRIPTION
**Pull request by dragoangel**
Particularly resolve #144

### CODE REVIEW

**Comment by dragoangel** [comment]
@catphish can you please merge this?

**Comment by rbozan** [comment]
I haven't tried it but doesn't this also queue messages that are held by using the development mode?

**Comment by dragoangel** [comment]
Hi @rbozan check `query=` code. It will not release anything from held except messages that was held due to rate limit.

**Comment by rbozan** [comment]
Ah OK awesome, I hope they will merge it but I think Postal isn't actively maintained 😔

**Comment by dragoangel** [comment]
you not only one who think so

**Comment by dragoangel** [comment]
😑, actually tested development mode, and it will release messages.  Need skip development server and credentials.

**Comment by willpower232** [comment]
Good spot @rbozan, the message should be aware of which credential it was recorded with so hopefully its only a minor change to the query.

Postal is maintained but unless there is a serious problem, the maintainers aren't likely to have the time to support it unfortunately.

**Comment by dragoangel** [comment]
@willpower232 what about broken dkim signing issue? This sirious issue

**Comment by dragoangel** [comment]
@rbozan can you check, looks like now Development will not be sent from held

**Comment by omueller** [comment]
Hi @dragoangel, I just noticed there are quite a lot of PR pending, and that the last commit here was about 6 months ago.   It seems @catphish left aTech/Krystal recently and last commit from @adamcooke was also while ago.  Is there any other person around with write access to the postalhq/postal repository?  

I just "discovered" this project a few days ago by looking for a system similar to sendgrid/mandrill but to be used "on premise", and Postal looks really great and very well-conceived.  I just hope it will not remain in this state too long:  support for Ubuntu 18.04 (cf. https://blog.h-educate.com/smtp-server-configuration/ for example or some PRs) or even 20.04 would for example be a must, as well as keeping all dependencies up to date.   Of course everything could just happen in a fork, but this is probably not optimal for the project.   

Best regards & I hope to read good news sometime some!  
Olivier

**Comment by dragoangel** [comment]
Hi @omueller can't say anything except that project unmaintained

**Comment by rbozan** [comment]
@omueller @dragoangel you can see in the Github network tab that there are some forks which merged some PRs, so these might help you, but personally for me I gave up on Postal and used good old Postfix for my use case.

**Comment by omueller** [comment]
Thanks @dragoangel and @rbozan for your feedbacks!   I see that for example @willpower232 is (very) active, especially on the gitlab Issues, but also that he doesn't have write rights to the repository : maybe you will be able to say more about the project status ?  Merci!

**Comment by willpower232** [comment]
I don't really have anything to add, Postal works really well for the majority of users but unfortunately the apparent time available from @adamcooke and the others who could maintain Postal isn't really compatible with the regular EOL'ing of ruby versions :sweat_smile: 

Even if someone with more time had write access to the repository, many people will be using the builds hosted by atech so would not have a pleasant upgrade path. We're using a manual merge of several changes to give us what we need but will be dockerising what we can at some point.

It would be better if more ruby developers were in here and could thoroughly test and review PRs, just to have some feedback about proposed changes and problems but as it stands, I don't know if there will be any further changes (minor or major) to Postal.

**Comment by omueller** [comment]
@dragoangel  it seems there is still some hope :-)  I just discovered the slack channel today (https://slack.k.io -> #postal, Krystal staff is visible there, @willpower232 too), and there was even a commit today 🥳 .   Let's see how this turns out!

**Review by htwmehdi — APPROVED** [review]

**Comment by adamcooke** [comment]
(I know this has been here for some time so apologies for the delayed update.)

I'm not sure the idea of dumping what could be a lot of held messages into the queue at exactly the same time is a good idea for performance. There are a few things which need to happen before this can be merged.

1. Ability to enable/disable this on a per-service basis.
2. Ability to spread the release into the queue over a longer period of time.
3. Messages that were held because their credential was in dev mode need to not be released.
4. Potentially, remove the need for this to be automatic and have it manually invoked with a "Release all held messages" button in the UI.

**Comment by adamcooke** [comment]
There's an outstanding issue for this which I'll refer this back to now. #257

**Comment by dragoangel** [comment]
But what about automation? There should be then a option to choose which way to work, auto or manual. Not think that people want to go end do release manually all the time. Point of limitations are to not extended sone amount of email per x time, but not block them totally. Also as postal is designed in first for mass mail it will be really cool future to handle how much can be send to one destination by two independent parameters, first is TO: and second is: mx domain with option for MX ends with to handle stuff like Outlook. If TO: is set and it has policy for mx as well, then TO: take advantage and do policy rate limits. What you think?

**Comment by adamcooke** [comment]
Can you start a discussion about this in the Discussions section so we don't lose it?

**Comment by dragoangel** [comment]
Hi @adamcooke did you had time to check this? https://github.com/postalserver/postal/discussions/1516

**Comment by niels-przybilla** [comment]
Hello @dragoangel ,

is your PR working also for Postal 2.0

**Comment by dragoangel** [comment]
Hi @niels-przybilla, not tested as not yet updated 😅. Generally I think yes, but this would mean you have to build docker image by yourself

**Comment by niels-przybilla** [comment]
Too bad ...

**Comment by dragoangel** [comment]
Bad that it's not merged and at same time not solved as it should

**Pull request closed without merging**
